CREATE TABLE "interviews" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"targetRecruitId" bigint,
	"meetingLink" varchar NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "interviews" ADD CONSTRAINT "interviews_targetRecruitId_target_recruits_id_fk" FOREIGN KEY ("targetRecruitId") REFERENCES "public"."target_recruits"("id") ON DELETE no action ON UPDATE no action;